// pages/class-dojo-remake.vue
<!-- ✅ File: pages/class-dojo-remake.vue -->
<template>
  <section class="space-y-6">
    <h1 class="text-2xl font-bold text-primary-600 dark:text-primary-400">Class Dojo Remake</h1>

    <div class="bg-white dark:bg-dark-surface rounded-lg shadow p-6">
      <p class="text-gray-700 dark:text-gray-300">
        Use this tool to manage student behavior, award points, and track engagement in your class.
      </p>

      <!-- Placeholder behavior point tracker -->
      <div class="mt-6 space-y-4">
        <div class="flex justify-between items-center border-b border-gray-200 dark:border-gray-700 pb-2">
          <span class="font-medium">John Doe</span>
          <span class="text-green-600 dark:text-green-400 font-semibold">+3</span>
        </div>
        <div class="flex justify-between items-center border-b border-gray-200 dark:border-gray-700 pb-2">
          <span class="font-medium">Jane Smith</span>
          <span class="text-green-600 dark:text-green-400 font-semibold">+5</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// Behavior logic can be added here
</script>

// src/routes/class-dojo-remake/+page.svelte
<script lang="ts">
  // Behavior logic can be added here
</script>

<section class="space-y-6">
  <h1 class="text-2xl font-bold text-primary-600 dark:text-primary-400">Class Dojo Remake</h1>

  <div class="bg-white dark:bg-dark-surface rounded-lg shadow p-6">
    <p class="text-gray-700 dark:text-gray-300">
      Use this tool to manage student behavior, award points, and track engagement in your class.
    </p>

    <!-- Placeholder behavior point tracker -->
    <div class="mt-6 space-y-4">
      <div
        class="flex justify-between items-center border-b border-gray-200 dark:border-gray-700 pb-2"
      >
        <span class="font-medium">John Doe</span>
        <span class="text-green-600 dark:text-green-400 font-semibold">+3</span>
      </div>
      <div
        class="flex justify-between items-center border-b border-gray-200 dark:border-gray-700 pb-2"
      >
        <span class="font-medium">Jane Smith</span>
        <span class="text-green-600 dark:text-green-400 font-semibold">+5</span>
      </div>
    </div>
  </div>
</section>
