// pages/lesson-planner.vue

<template>
  <section class="space-y-6">
    <h1 class="text-2xl font-bold text-primary-600 dark:text-primary-400">Lesson Planner</h1>

    <div class="bg-white dark:bg-dark-surface rounded-lg shadow p-6">
      <p class="text-gray-700 dark:text-gray-300">
        Plan and schedule lessons for your classes. You can outline objectives, assign resources, and track progress.
      </p>

      <!-- Placeholder Lesson Plan Table -->
      <div class="overflow-x-auto mt-6">
        <table class="min-w-full text-sm text-left border border-gray-200 dark:border-gray-700">
          <thead class="bg-gray-100 dark:bg-gray-800">
            <tr>
              <th class="p-3 font-semibold">Date</th>
              <th class="p-3 font-semibold">Subject</th>
              <th class="p-3 font-semibold">Lesson Topic</th>
              <th class="p-3 font-semibold">Materials</th>
            </tr>
          </thead>
          <tbody>
            <tr class="border-t border-gray-200 dark:border-gray-700">
              <td class="p-3">2025-05-05</td>
              <td class="p-3">Math</td>
              <td class="p-3">Fractions Intro</td>
              <td class="p-3">Slides, worksheet</td>
            </tr>
            <tr class="border-t border-gray-200 dark:border-gray-700">
              <td class="p-3">2025-05-06</td>
              <td class="p-3">Science</td>
              <td class="p-3">Photosynthesis</td>
              <td class="p-3">Diagram, video</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// Lesson planner logic here (future editable)
</script>

// src/routes/lesson-planner/+page.svelte
<script lang="ts">
	// Lesson planner logic here (future editable)
</script>

<section class="space-y-6">
	<h1 class="text-2xl font-bold text-primary-600 dark:text-primary-400">Lesson Planner</h1>

	<div class="bg-white dark:bg-dark-surface rounded-lg shadow p-6">
		<p class="text-gray-700 dark:text-gray-300">
			Plan and schedule lessons for your classes. You can outline objectives, assign resources, and
			track progress.
		</p>

		<!-- Placeholder Lesson Plan Table -->
		<div class="overflow-x-auto mt-6">
			<table class="min-w-full text-sm text-left border border-gray-200 dark:border-gray-700">
				<thead class="bg-gray-100 dark:bg-gray-800">
					<tr>
						<th class="p-3 font-semibold">Date</th>
						<th class="p-3 font-semibold">Subject</th>
						<th class="p-3 font-semibold">Topic</th>
						<th class="p-3 font-semibold">Resources</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="p-3">2025-05-06</td>
						<td class="p-3">Science</td>
						<td class="p-3">Photosynthesis</td>
						<td class="p-3">Diagram, video</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>
